server:
  port: 8080

spring:
  # 数据库数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/magic_valorant
    username: root
    password: 1234
  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      database: 0

# 小程序配置
mini-app:
  app-id: app-id
  app-secret: app-secret

# 阿里云OSS配置
aliyun:
  oss:
    region: test-region
    endpoint: test-endpoint
    access-key-id: test-access-key-id
    access-key-secret: test-access-key-secret
    bucket-name: test-bucket-name

# 跨域配置
cors:
  # 允许访问的源
  allowed-origins: "*"

# 日志配置
logging:
  level:
    root: info
  custom:
    # 日志文件夹路径
    path: ./logs
    # 单个日志文件最大大小
    max-file-size: 100MB
    # 保留天数（默认 -1 表示永久保留）
    max-history: -1

# Token 配置
token:
  # Token 在 Redis 存放的 key 前缀
  redis-prefix: token
  # 发放登录令牌的有效期（秒）
  login-ttl: 3600
  # 发放临时令牌的有效期（秒）
  temp-ttl: 10

# 验证码配置
captcha:
  expire:
    # 验证码过期时间（毫秒）
    default: 5000