server:
  port: 8080

spring:
  # 数据库数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/magic_valorant
    username: root
    password: 1234
  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      database: 0

# 跨域配置
cors:
  # 允许访问的源
  allowed-origins: http://localhost:5173/