spring:
  data:
    # Redis 配置
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      database: 0
      lettuce:
        pool:
          # 最大连接
          max-active: 8
          # 最大空闲连接
          max-idle: 8
          # 最小空闲连接
          min-idle: 0
          # 等待时间
          max-wait: 100ms