spring:
  application:
    name: backend
  profiles:
    # 当前生效的环境配置
    active: dev
  # 数据库数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    # Redis 配置
    redis:
      lettuce:
        pool:
          # 最大连接
          max-active: 8
          # 最大空闲连接
          max-idle: 8
          # 最小空闲连接
          min-idle: 0
          # 等待时间
          max-wait: 100ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

mybatis:
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: top.lhlnb.backend.domain.entity

# 跨域配置
cors:
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    - X-Forwarded-For
    - X-Real-IP
  allow-credentials: false

# 日志配置
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss SSS}]%highlight([%-5level])[%15.15t] %cyan(%-45.45logger{40}): %msg%n"

jwt:
  # JWT 密钥
  secret: test-secret
  # 默认有效期(秒)
  ttl: 60

# 滑块验证码配置
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中，这里配置redis的key的前缀,默认是captcha:slider
  prefix: captcha
  # 验证码过期时间，默认是2分钟,单位毫秒，可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 5000
    # 针对 点选验证码 过期时间设置为 2分钟，因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 20000
  # 使用加载系统自带的资源， 默认是 false(这里系统的默认资源包含 滑动验证码模板/旋转验证码模板,如果想使用系统的模板，这里设置为true)
  init-default-resource: false
  # 缓存控制， 默认为false不开启
  local-cache-enabled: true
  # 缓存开启后，验证码会提前缓存一些生成好的验证数据， 默认是20
  local-cache-size: 20
  # 缓存开启后，缓存拉取失败后等待时间 默认是 5秒钟
  local-cache-wait-time: 5000
  # 缓存开启后，缓存检查间隔 默认是2秒钟
  local-cache-period: 2000
  # 配置字体包，供文字点选验证码使用,可以配置多个，不配置使用默认的字体
  font-path:
  # - classpath:font/SimHei.ttf
  secondary:
    # 二次验证， 默认false 不开启
    enabled: false
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    keyPrefix: "captcha:secondary"
